remote_theme: just-the-docs/just-the-docs

defaults:
  - scope:
      path: "content" # Applies settings to all files in the "content" folder
      type: "pages"
    values:
      layout: "default"

includes:
  - mathjax_support.html
