remote_theme: just-the-docs/just-the-docs
defaults:
  - scope:
      path: "content" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: false
