remote_theme: just-the-docs/just-the-docs
defaults:
  - scope:
      path: "content" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
markdown: kramdown

    kramdown: 

      input: GFM

      hard_wrap: false

      math_engine: MathJax
